//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanBida.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuNhap
    {
        public string MaPN { get; set; }
        public string MaSP { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<double> GiaNhap { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
        public string Ma { get; set; }
    
        public virtual SanPham SanPham { get; set; }
    }
}
